In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df=pd.read_csv("train.txt",sep=";",header= None,names=["text","emotion"])

In [4]:
df.head

<bound method NDFrame.head of                                                     text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...  sadness
15996  i am now turning and i feel pathetic that i am...  sadness
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

[16000 rows x 2 columns]>

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
unique_emotions=df["emotion"].unique()
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1

df["emotion"]=df["emotion"].map(emotion_numbers)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [8]:
df["text"]=df["text"].apply(lambda x:x.lower())#to convert whole text into lower text

In [9]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

TO REMOVE PUNCTUATION

In [10]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [11]:
df["text"]=df["text"].apply(remove_punc)

TO REMOVE NUMBERS

In [12]:
def remove_numbers(txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new=new+i
    return new
df["text"]=df["text"].apply(remove_numbers)

In [13]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new
df["text"]=df["text"].apply(remove_emojis)

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [16]:
nltk.download("punkt")#to convert words into tokens
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
stop_words =set(stopwords.words("english"))
len(stop_words)

198

In [18]:
df.loc[1]["text"]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [19]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [20]:
def remove(txt):
    words=word_tokenize(txt)
    cleaned=[]
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [21]:
df["text"]=df["text"].apply(remove)

In [22]:
df.loc[1]["text"]

'go feeling hopeless damned hopeful around someone cares awake'

In [24]:
from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer(ngram_range= (1,3))

X = vectorizer.fit_transform(df["text"])

print("vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n",X)

vocabulary: ['aa' 'aa full' 'aa full force' ... 'zz' 'zz top' 'zz top logo']

BoW Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 395095 stored elements and shape (16000, 222650)>
  Coords	Values
  (0, 40736)	1
  (0, 57144)	1
  (0, 96704)	1
  (0, 40785)	1
  (0, 60932)	1
  (0, 40817)	1
  (1, 83742)	1
  (1, 67235)	1
  (1, 95184)	1
  (1, 36479)	1
  (1, 95072)	1
  (1, 9316)	1
  (1, 178508)	1
  (1, 23932)	1
  (1, 11652)	1
  (1, 83884)	1
  (1, 69188)	1
  (1, 95199)	1
  (1, 36483)	1
  (1, 95075)	1
  (1, 9635)	1
  (1, 178547)	1
  (1, 23933)	1
  (1, 83887)	1
  (1, 69190)	1
  :	:
  (15998, 114767)	1
  (15998, 61777)	1
  (15998, 83290)	1
  (15998, 166385)	1
  (15998, 29502)	1
  (15998, 117561)	1
  (15998, 62330)	1
  (15998, 99176)	1
  (15998, 166399)	1
  (15998, 29515)	1
  (15998, 117563)	1
  (15998, 166400)	1
  (15998, 29516)	1
  (15999, 57144)	1
  (15999, 108771)	1
  (15999, 122678)	1
  (15999, 186861)	1
  (15999, 151672)	1
  (15999, 65633)	1
  (15999, 122743)	1
  (15999, 109400)	1
  (15999, 186970)	1
  (15999, 109403)	1
  (15999, 122748)	1
  (15999, 65650)	1

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer


vectorizer = TfidfVectorizer(ngram_range= (1,3))

X = vectorizer.fit_transform(df["text"])

print("vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n",X)

vocabulary: ['aa' 'aa full' 'aa full force' ... 'zz' 'zz top' 'zz top logo']

BoW Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 395095 stored elements and shape (16000, 222650)>
  Coords	Values
  (0, 40736)	0.32088326498957315
  (0, 57144)	0.08831439644636091
  (0, 96704)	0.4242143962994056
  (0, 40785)	0.3747971368549421
  (0, 60932)	0.45623084214609194
  (0, 40817)	0.6005473907047492
  (1, 83742)	0.11266919064918242
  (1, 67235)	0.051569415510511134
  (1, 95184)	0.1545536511550834
  (1, 36479)	0.21548527066733547
  (1, 95072)	0.1564551046065937
  (1, 9316)	0.11729041709038443
  (1, 178508)	0.1232279047955147
  (1, 23932)	0.1878540574536023
  (1, 11652)	0.18255317386081815
  (1, 83884)	0.20432010585686097
  (1, 69188)	0.1878540574536023
  (1, 95199)	0.23725220266337832
  (1, 36483)	0.23725220266337832
  (1, 95075)	0.22762018181241256
  (1, 9635)	0.22762018181241256
  (1, 178547)	0.22078615426011966
  (1, 23933)	0.23725220266337832
  (1, 83887)	0.23725220266337832
  (1, 69190)	0.23725220266337832
  :	:
  (15998, 114767)	0.0935720891842867
  (15998, 61777)	0.10823981668314595
  (15998, 83290)	0.207619338077064
  (15998, 166385)	0.22256047477586782
  (15998, 29502)	0.2529922237655334
  (15998, 117561)	0.2928807615155365
  (15998, 62330)	0.30416318020794875
  (15998, 99176)	0.2673250626091504
  (15998, 166399)	0.33488778258463525
  (15998, 29515)	0.33488778258463525
  (15998, 117563)	0.33488778258463525
  (15998, 166400)	0.33488778258463525
  (15998, 29516)	0.33488778258463525
  (15999, 57144)	0.050855660132681176
  (15999, 108771)	0.14350061211363158
  (15999, 122678)	0.18967875053609431
  (15999, 186861)	0.21485500815372463
  (15999, 151672)	0.3273873532519073
  (15999, 65633)	0.26271957442771643
  (15999, 122743)	0.315243473143002
  (15999, 109400)	0.315243473143002
  (15999, 186970)	0.36045791177560393
  (15999, 109403)	0.36045791177560393
  (15999, 122748)	0.36045791177560393
  (15999, 65650)	0.36045791177560393

In [27]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
df["text"],df["emotion"], test_size=0.20, random_state=42)

In [28]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [29]:
bow_vectorizer=CountVectorizer()

In [40]:
X_train_bow =bow_vectorizer.fit_transform(X_train)
X_test_bow =bow_vectorizer.transform(X_test)

In [41]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [42]:
nb_model = MultinomialNB()

In [43]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [44]:
pred_nb = nb_model.predict(X_test_bow)

In [45]:
pred_nb

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [46]:
Tfidf_vectorizer=TfidfVectorizer()
X_train_Tfidf =Tfidf_vectorizer.fit_transform(X_train)
X_test_Tfidf =Tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_Tfidf,y_train)

MultinomialNB()

In [47]:
pred_nb2 =nb2_model.predict(X_test_Tfidf)

In [49]:
pred_nb2

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
Logistic_model = LogisticRegression(max_iter=1000)

In [52]:
Logistic_model.fit(X_train_Tfidf,y_train)

LogisticRegression(max_iter=1000)

In [53]:
log_pred =Logistic_model.predict(X_test_Tfidf)

In [54]:
print(accuracy_score(y_test,log_pred))

0.8615625